### ISSUE TITLE
虚线的问题

### ISSUE THREAD

**Issue by jiaweio** [IvanRich/MonthBill#1]
你好，请问你的Demo应用截图后两个月的虚线是如何实现的 我运行你的demo 得到的是最后一截是虚线其他的都是实线勾画的

**Comment by neo1949** [comment]
虚线和实线是根据 [MainActivity.java](https://github.com/neo1949/MonthBill/blob/master/app/src/main/java/rich/ivan/monthbill/MainActivity.java) 中 mBillValues 数组值绘制的，你可以使用我提供的几个数组测试，就可以看到不同的绘制效果了。

**Comment by jiaweio** [comment]
嗯嗯 我之前没有看仔细  现在已经解决了 谢谢🙏
